apiVersion: v1
kind: Service
metadata:
  name: teams-app
  namespace: integrations
  labels:
    app: teams-app
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    app: teams-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teams-app
  namespace: integrations
  labels:
    app: teams-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teams-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: teams-app
    spec:
      containers:
        - name: teams-app
          image: docker.io/{{DOCKERHUB_USERNAME}}/fyle_teams-app:{{RELEASE_VERSION}}
          resources:
            limits:
              memory: 200Mi
            requests:
              memory: 200Mi
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 1
          envFrom:
            - secretRef:
                name: teams-app-secrets
      terminationGracePeriodSeconds: 60
      imagePullSecrets:
        - name: myregistrykey2
